[theme]
base = "dark"
primaryColor = "#ea580c"
backgroundColor = "#070707"
secondaryBackgroundColor = "#0e0e0e"
textColor = "#f0f0f0"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
